server:
  port: 10010

spring:
  application:
    name: spring-user
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/user.db

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.user.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.user.mapper: debug

encryption:
  aes-key: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=
  key-type: FIXED
